name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Clean install dependencies and build
      run: |
        .\scripts\Initialize-BuildEnv.ps1
        build
        pack
