name: CI-Build
on:
  push:
    branches:
      - develop
      - llvm_20

    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - develop
      - llvm_20

jobs:
  build_target:
    strategy:
       matrix:
         LlvmAdditionalTarget: [
             AArch64,
             AMDGPU,
             ARM,
             AVR,
             BPF,
             Hexagon,
             Lanai,
             LoongArch,
             Mips,
             MSP430,
             NVPTX,
             PowerPC,
             RISCV,
             Sparc,
             SPIRV,
             SystemZ,
             VE,
             WebAssembly,
             X86,
             XCore
         ]
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build Source
        shell: pwsh
        run: .\Build-NativeAndOneTarget.ps1 -ForceClean -AdditionalTarget '${{ matrix.LlvmAdditionalTarget }}'

      - name: Upload build logs
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: BuildLogs-win-x64-${{ matrix.LlvmAdditionalTarget }}
          path: .\BuildOutput\BinLogs

      - name: Upload NuGET Packages
        uses: actions/upload-artifact@v4
        with:
          name: win-x64-${{ matrix.LlvmAdditionalTarget }}
          path: .\BuildOutput\Nuget

  build_meta_package:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build RID specific Metapackage
        shell: pwsh
        run: .\Build-Package.ps1

      - name: Upload RID specific Meta Package
        uses: actions/upload-artifact@v4
        with:
          name: win-x64-meta-package
          path: .\BuildOutput\Nuget
