name: CI-Build
on:
  push:
    branches:
      - develop
      - llvm_20
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - develop
      - llvm_20

    paths-ignore:
      - '**.md'

jobs:
  build_target:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build Source
        shell: pwsh
        run: .\Build-LibLLVMAndPackage.ps1 -FullInit

      - name: Upload build logs
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: BuildLogs-win-x64
          path: .\BuildOutput\BinLogs

      - name: Upload NuGET Packages
        uses: actions/upload-artifact@v4
        with:
          name: win-x64-nuget
          path: .\BuildOutput\Nuget

  build_handle_package:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build Handle Source package
        shell: pwsh
        run: .\Build-HandlesPackage.ps1 -FullInit

      - name: Upload Handle Package
        uses: actions/upload-artifact@v4
        with:
          name: interop-handle-package
          path: .\BuildOutput\Nuget
