name: CI-Build
on:
  push:
    branches:
      - develop
      - llvm_20

    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - develop
      - llvm_20

jobs:
  build_target:
    strategy:
       matrix:
         LlvmAdditionalTarget: [
             "AArch64",
             "AMDGPU",
             "ARM",
             "AVR",
             "BPF",
             "Hexagon",
             "Lanai",
             "LoongArch",
             "Mips",
             "MSP430",
             "NVPTX",
             "PowerPC",
             "RISCV",
             "Sparc",
             "SPIRV",
             "SystemZ",
             "VE",
             "WebAssembly",
             "X86",
             "XCore"
         ]
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build Source
        run: .\Build-NativeAndOneTarget.ps1 -ForceClean ${{ matrix.LlvmTarget }}

      - name: Publish build logs
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v1
        with:
          name: Build Logs
          path: .\BuildOutput\BinLogs

      - name: Publish NuGET Packages
        uses: actions/upload-artifact@v1
        with:
          name: Nuget Packages
          path: .\BuildOutput\Nuget

  build_meta_package:
    needs: build_target
    runs-on: windows-latest
    steps:
      - name: Build RID specific Metapackage
        run: .\Build-Package.ps1

      - name: Upload RID specific Meta Package
        uses: actions/upload-artifact@v1
        with:
          name: Nuget Packages
          path: .\BuildOutput\Nuget
